In [5]:
import numpy as np

In [7]:
array_calculo = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_calculo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
soma = np.add(array_calculo, 10)
soma

In [ ]:
multiplicacao = np.multiply(array_calculo, 5)
multiplicacao

In [ ]:
divisao = np.divide(multiplicacao, 5)
divisao

In [ ]:
media = np.mean(array_calculo)
media

In [ ]:
desvioPadrao = np.std(array_calculo)
desvioPadrao

In [8]:
subtracao = np.subtract(array_calculo, 5)
subtracao

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [9]:
maximo = np.max(array_calculo)
maximo

9

In [10]:
minimo = np.min(array_calculo)
minimo

0

In [12]:
raiz_maximo = np.sqrt(maximo)
raiz_maximo

3.0

In [13]:
mascara = array_calculo > 3
mascara

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [14]:
mascara = array_calculo[mascara]
mascara

array([4, 5, 6, 7, 8, 9])

In [15]:
exponencial = np.power(array_calculo, 2)
exponencial

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [16]:
logaritmo = np.log(exponencial)
logaritmo

C:\Users\Filipe\AppData\Local\Temp\ipykernel_2260\2615797185.py:1: RuntimeWarning: divide by zero encountered in log
  logaritmo = np.log(exponencial)


array([      -inf, 0.        , 1.38629436, 2.19722458, 2.77258872,
       3.21887582, 3.58351894, 3.8918203 , 4.15888308, 4.39444915])