In [1]:
import numpy as np

In [6]:
array_2dimensao = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
fatia_array2 = array_2dimensao[0:2, 0:2]
fatia_array2

array([[1, 2],
       [4, 5]])

In [8]:
fatia_array2[0, 1] = 10
array_2dimensao

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [13]:
copia_array = array_2dimensao.copy()
copia_array
copia_array[0, 1] = 2
copia_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
array_2dimensao

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])