In [1]:
import numpy as np

In [2]:
array_1dimensao = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1dimensao

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arrayReshape = np.reshape(array_1dimensao, [3, 3])
arrayReshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arrayReshape2 = array_1dimensao.reshape(3, -1)
arrayReshape2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])